FROM node:12-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY ./ .
RUN npm run build

FROM nginx:alpine
RUN mkdir /app
COPY --from=build-stage /app/web/ /app
COPY ./web/nginx.conf /etc/nginx/nginx.conf