name: JavaScript files

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install lerna
      run: npm install
    - name: Install packages
      run: npm run install:ci
    - name: Lint code
      run: npm run lint
    - name: Build packages
      run: npm run build