name: JavaScript files

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install lerna
      run: yarn install
    - name: Lint code
      run: yarn run lint
    - name: Install packages
      run: yarn run install:ci
    - name: Build packages
      run: yarn run build
    - name: Build NodeJS release files
      run: ./scripts/release-bin.sh
      working-directory: ./packages/cli-device-node
    - name: Update the Release
      uses: johnwbyrd/update-release@master
      if: github.ref == 'refs/heads/v2'
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release: Cutting Edge
        files: >
          ./packages/cli-device-node/dist/h1-linux.tar.gz
          ./packages/cli-device-node/dist/h1-alpine.tar.gz
          ./packages/cli-device-node/dist/h1-macos.tar.gz
        draft: false