name: JavaScript files

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install lerna
      run: yarn install
    - name: Lint code
      run: yarn run lint
    - name: Install packages
      run: yarn run install:ci
    - name: Build packages
      run: yarn run build
    - name: Build NodeJS release files
      run: ./scripts/release-bin.sh
      working-directory: ./packages/cli-device-node
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - uses: octokit/request-action@v2.x
      id: get_rc_release
      with:
        route: GET /repos/:repository/releases/28758119
        repository: ${{ github.repository }}
        # Use following to identify new release id:
        # curl https://api.github.com/repos/hyperonecom/h1-cli/releases
        # -H "Authorization: token $GH_TOKEN"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset of h1-linux.tar.gz
      id: h1-linux-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ fromJson(steps.get_rc_release.outputs.data).upload_url }}
        asset_path: ./packages/cli-device-node/dist/h1-linux.tar.gz
        asset_name: h1-linux.${{ steps.slug.outputs.sha8 }}.tar.gz
        asset_content_type: application/gzip
    - name: Upload Release Asset of h1-alpine.tar.gz
      id: h1-alpine-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ fromJson(steps.get_rc_release.outputs.data).upload_url }}
        asset_path: ./packages/cli-device-node/dist/h1-alpine.tar.gz
        asset_name: h1-alpine.${{ steps.slug.outputs.sha8 }}.tar.gz
        asset_content_type: application/gzip
    - name: Upload Release Asset of h1-macos.tar.gz
      id: h1-macos-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ fromJson(steps.get_rc_release.outputs.data).upload_url }}
        asset_path: ./packages/cli-device-node/dist/h1-macos.tar.gz
        asset_name: h1-macos.${{ steps.slug.outputs.sha8 }}.tar.gz
        asset_content_type: application/gzip
    - name: Upload Release Asset of h1-win.zip
      id: h1-win-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ fromJson(steps.get_rc_release.outputs.data).upload_url }}
        asset_path: ./packages/cli-device-node/dist/h1-win.zip
        asset_name: h1-win.${{ steps.slug.outputs.sha8 }}.zip
        asset_content_type: application/zip
    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          Use following link to download pre-compiled binary:
          - [h1-linux.tar.gz][${{ steps.h1-linux-asset.outputs.browser_download_url }}]
          - [h1-alpine.tar.gz][${{ steps.h1-alpine-asset.outputs.browser_download_url }}]
          - [h1-macos.tar.gz][${{ steps.h1-macos-asset.outputs.browser_download_url }}]
          - [h1-win.zip][${{ steps.h1-win-asset.outputs.browser_download_url }}]